title:              Youtube Analysis
email:              your-email@example.com
description:        Analyzing youtube over the years
author:             NaN
baseurl:            ""
url:                "https://ahmadelrouby.startbootstrap.github.io/youtube-analysis"

# Social Profiles
twitter_username:   nan
github_username:    nan
facebook_username:  nan
instagram_username:  nan
linkedin_username: nan

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
